//câu 1
//câu 2
//câu 3
SELECT DX.DongXe 
FROM DONGXE DX
WHERE DX.SoChoNgoi > 5
//câu 4
SELECT NCC.MaNhaCC, NCC.TenNhaCC
FROM NHACUNGCAP NCC JOIN DANGKYCUNGCAP DK
ON NCC.MaNhaCC = DK.MaNhaCC
JOIN MUCPHI MP
ON MP.MaMp = DK.MaMp
JOIN DONGXE DX
ON DX.DongXe = DK.DongXe
WHERE (DX.HangXe = 'Toyota' and MP.DonGia = 15000) or (DX.HangXe = 'KIA' and MP.DonGia = 20000)
//câu 5
SELECT *
FROM NHACUNGCAP NCC
ORDER BY NCC.TenNhaCC DESC, NCC.MaSoThue ASC
//câu 6
SELECT NCC.MaNhaCC, NCC.TenNhaCC, count(NCC.MaNhaCC) as SoLanCC
FROM NHACUNGCAP NCC JOIN DANGKYCUNGCAP DK
ON NCC.MaNhaCC = DK.MaNhaCC
WHERE DK.NgayBatDauCungCap = '20/11/2015'
GROUP BY NCC.MaNhaCC, NCC.TenNhaCC
//câu 7
SELECT DX.HangXe
FROM DONGXE DX
GROUP BY DX.HANGXE
//câu 8
SELECT MaDKCC, MaNhaCC, TenNhaCC, DiaChi, MaSoThue, TenLoaiDV, DonGia,
HangXe, NgayBatDauCC, NgayKetThucCC 
FROM NHACUNGCAP NCC JOIN DANGKYCUNGCAP DK 
ON NCC.MaNhaCC = DK.MaNhaCC 
JOIN MUCPHI MP 
ON MP.MaMp = DK.MaMp 
JOIN LOAIDICHVU DV
ON DV.MaLoaiDV = DK.MaLoaiDV
//câu 9
SELECT NCC.MaNhaCC, NCC.TenNhaCC
FROM NHACUNGCAP NCC 
WHERE NCC.MaNhaCC in (
SELECT DK.MaNhaCC
FROM DANGKYCUNGCAP DK
WHERE DK.DongXe = 'Hiace' or DK.DongXe = 'Cerato')
//câu 10
SELECT NCC.MaNhaCC, NCC.TenNhaCC
FROM NHACUNGCAP NCC 
WHERE not exists(
SELECT *
FROM DANGKYCUNGCAP DK
WHERE NCC.MaNhaCC = DK.MaNhaCC)
